# config.yaml
storage:
  type: "flask"  # Options: "memory", "local_storage", "postgres", "dynamo", etc.
  options:
    # Additional options specific to the storage type
    # For example, for Postgres:
    host: "redis"
    port: 6379
    db: 2
    database: 2
    # user: "user"
    # password: "password"